### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by spwalgren** [spwalgren/Student-Budget-Tracker#1]
As a site user, I want to be able to log in to the website to save my personal information.

**Comment by Brian-Magnuson** [comment]
# Features

- User is presented with a form to import their username and password
- If username or password does not match records, user is denied access with warning message
- User has the option to sign up to register their username and password
- If username and password matches records, user is granted access and is taken to the main page

**Comment by emilyjiji** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/92887308/215816898-7214a0d3-e23b-4890-8af2-9e46a39b075d.png">

YouTube link: https://www.youtube.com/watch?v=C1F2pJzq5xQ

-Simple version of login page
-Afterwards we can add:
-login with google
-remember me
-forgot password

**Comment by Brian-Magnuson** [comment]
Current progress on login page:
![msedge_SWcFPxoqtm](https://user-images.githubusercontent.com/92892499/216645781-1994207e-082c-4720-8560-ecd6a96f602e.gif)
![msedge_UtMvMswUNg](https://user-images.githubusercontent.com/92892499/216645796-8a26dd27-6492-4db0-b728-f8068c73db9a.gif)

**Comment by Brian-Magnuson** [comment]
![msedge_W4cTbtfuZ4](https://user-images.githubusercontent.com/92892499/218505477-fd8dfdfc-4d32-468e-8094-688a99c0599e.gif)

Finished login and logout system. Should pull request shortly.
