### ISSUE TITLE
Adding Login

### ISSUE THREAD

**Issue by emilyjiji** [spwalgren/Student-Budget-Tracker#11]
As a frequent user, I want to open my budget without having to log in each time, so I can access my budget tracker faster.

**Comment by Brian-Magnuson** [comment]
Our app already does this. Cookies are stored for a day and allow automatic login until the user manually presses log out or his or her cookie expires.

![msedge_pi4eemSOj3](https://user-images.githubusercontent.com/92892499/227568590-1d6fd038-a8a9-48af-ab50-a7e46701b9fc.gif)
