### ISSUE TITLE
Adding Transactions

### ISSUE THREAD

**Issue by emilyjiji** [spwalgren/Student-Budget-Tracker#3]
As a site user, I want to be able to easily add an expense so that my progress can be tracked.

**Comment by Brian-Magnuson** [comment]
A transaction will be a single record of a person's earnings or expenses. They are essential to this project as other systems, such as "goals" or "trends", will depend on this data. It is essential that we give the user a way to record their transactions and save them in a database, and then give the user a way to view them later.

## Features

- Transactions are accessible from the dashboard
- Transactions can be viewed as a table of entries
- Transactions contain info about the name, description, date, amount, and category
- Users can sort/filter their transactions by any of the previous
- Users can click a button to add a new transaction
- The process of adding a transaction is quick and simple and can supply the needed information to the backend
- Users can edit transactions
- Users can delete transactions

**Comment by Brian-Magnuson** [comment]
![image](https://user-images.githubusercontent.com/92892499/220189279-78fdadb4-50ea-487c-92a7-6d2b1bb89683.png)
Transactions table currently looks like this. Rows can be expanded; we can use this to show descriptions of transactions that a user might add.

![image](https://user-images.githubusercontent.com/92892499/220189444-989de6a8-2bc1-4258-afd7-fd0e0ed49f2d.png)
Pages that don't exist display a 404 component.
